Move articles about the third-party tools and libs
oat-sa/taohub-articles pull request #21
Opened 2017-05-09 07:40 UTC by jsconan

Move articles related to the third party tools and libraries from the backup of the forge wiki to the articles

2017-05-09 07:49 UTC, dietertaotesting commented on articles/Third Party Tools and Libraries/enable-math.md
> +parent: articles
Parent is the category under which an article is listed e.g. on https://hub.taocloud.org/articles (Administrator Guide, Data Abstractions etc.). If set at all it should be in proper spelling, not lower case etc. On the other hand you can ommit it. In this case the directory name will be used.
Example:
taohub-articles/articles/Some Category/my-article.md (assumed the title is My Article)
will be displayed as
**Some Category**
  - My Article

2017-05-09 07:51 UTC, dietertaotesting commented on articles/Third Party Tools and Libraries/enable-math.md
> +    - 'ThirdParty'
Tags are mainly used to build the navigation from https://hub.taocloud.org/taohubdocs/tags-and-tag-groups, not so much as keywords for search. Insofar ThirdParty or Library are not ideal

2017-05-09 07:53 UTC, dietertaotesting commented on articles/Third Party Tools and Libraries/enable-math.md
> +An already shrunk Mathjax archive is available [here](../resources/third-party/mathjax-shrinked.zip).
Spelling: mathjax-shrinked should also be shrunk (http://www.verbix.com/webverbix/English/shrink.html)

2017-05-09 07:58 UTC, dietertaotesting commented on articles/Third Party Tools and Libraries/enable-math.md
> +> It supports both MathML and LaTex expressions.
The combination title -> synopsis as one line -> logo is well tested, this order not so much. I'm pretty curious to see if this passes my parser with the expected result. We'll see :-)

2017-05-09 08:01 UTC, dietertaotesting commented on articles/Third Party Tools and Libraries/pdf-printing.md
> +
You could mention, that there is also a binary for Windows on https://wkhtmltopdf.org/downloads.html, but that this has not been tested by us.

2017-05-09 08:03 UTC, dietertaotesting commented on forge/QTI-in-TAO.md
>  As to PDF files, the issue is the same as math expressions and multimedia. There is no way to ensure cross-browser compatibility natively. Currently, pdf files are therefore not fully supported in TA
what ist this ref to #2503? Is the link correct, also is the <br> required?

2017-05-09 08:04 UTC, ghost requested changes
Please read the comments in https://github.com/oat-sa/taohub-articles/pull/21/files#diff-24a08789514e82e23208f463a3adc88a first as they apply to other files too

2017-05-11 07:01 UTC, jsconan commented
Changes made

2017-05-11 11:17 UTC, ghost approved these changes

2017-05-11 11:17 UTC, merged