Frontend work station
oat-sa/taohub-articles pull request #32
Opened 2018-09-13 11:52 UTC by rkarolis

New article for ESLint in Windows

2018-09-13 12:21 UTC, no-chris requested changes
Nice typos corrections!  👍 
Good first draft on the new page, I have a few remarks to make it more generic

2018-09-14 14:49 UTC, no-chris requested changes

2018-09-14 14:49 UTC, no-chris commented on articles/Installation and Upgrading/setup-eslint-on-windows-workstation.md
> +Install Node.js and install ESLint globally with command `npm i -g eslint`.
Please add the path of the eslint config file in TAO

2018-09-14 14:49 UTC, no-chris commented on articles/Installation and Upgrading/install-from-config-file.md
> +php tao/scripts/taoSetup.php /path/to/your/configFile.json -vvv
I think it's enough with the Windows difference above, repeating the command twice can be confusing

2018-09-14 14:49 UTC, no-chris commented on articles/Installation and Upgrading/install-from-config-file.md
> +php tao/scripts/taoSetup.php /path/to/your/configFile.json -vvvv -nc
same here

2018-10-04 13:03 UTC, dietertaotesting commented on articles/Installation and Upgrading/setup-eslint-on-windows-workstation.md
> +
Please use the following convention for paths:
- The root directory is the one that contains all extensions
- Use forward slashes, even when your environment is Windows
The path would then be _tao/views/build/.eslintrc.json_

2018-10-04 13:24 UTC, ghost reviewed
This is actually not bad all. Some of the code has broken formatting which is a well known problem. You are _not_ expected to fix the formatting problems, unless the changes are tiny. Wait until after the workshop to learn more about formatting before you do anything

2018-10-12 14:04 UTC, ghost requested changes
Make sure you checkout in Unix style
https://help.github.com/articles/dealing-with-line-endings/

2018-10-12 14:33 UTC, merged