Rewritten tutorial + associated files
oat-sa/taohub-articles pull request #33
Opened 2018-10-03 13:29 UTC by oatymart

FAO @no-chris and @dietertaotesting 

Let me know your thoughts

2018-10-04 13:34 UTC, ghost reviewed
Under the assumption that this tutorial is correct this is actually really good. You may want to review this article after the workshop on documentation

2018-10-04 13:34 UTC, dietertaotesting commented on forge/How to make a new extension 3 3/how-to-make-a-new-extension-3-3.md
> +
Don't mix "hash" notation with underline notation when making headings, hashes are preferred

2018-10-04 13:34 UTC, dietertaotesting commented on forge/How to make a new extension 3 3/how-to-make-a-new-extension-3-3.md
> +    (If you wish, you can select some Samples to generate extra structure).
Can you find a more generic name? I would probaly go for something like _taoSomeMeaningfulName_

2018-10-04 14:17 UTC, ghost requested changes
Please update after doc workshop, see inline comments

2018-10-08 09:51 UTC, oatymart commented
I agree, I wondered why `taoDocs` was used. I think the suggestion of `taoSomeMeaningfulName` is a bit long, how about I rename it `taoPlayground`?

2018-10-08 11:42 UTC, dietertaotesting commented
`taoPlayground` could be a real thing. In fact we have a test server called `playground` and `spielplatz` on the other test server is German for `playground`, so you that might cause confusion. You could something like `taoExample|Mock|Dummy|Sample` instead. Don't worry about the length of the name though.

2018-10-10 07:06 UTC, dietertaotesting commented on forge/How to make a new extension 3 3/how-to-make-a-new-extension-3-3.md
> +
Link this to the article on GitHub instead, use a proper md link
https://github.com/oat-sa/taohub-articles/blob/master/forge/Wiki/installing-a-new-extension.md

2018-10-10 07:16 UTC, ghost reviewed
All screen shots refer to `taoDocs`, which is wrong for two reasons
- the extension is now called `taoExample`
- more importantly you would not have the label `taoDocs` or `taoExample` in the menu - you would have `Docs` or `Example` instead. 
I suggest you figure out how this is done (in `structures.xml`), describe and make new shots (or use https://pixlr.com/editor/ or something like that)

2018-10-10 07:21 UTC, oatymart commented
You are right of course. I will look into editing or redoing the screenshots.

2018-10-12 13:10 UTC, merged